### ISSUE TITLE
No clear example on how to use PBE

### ISSUE THREAD

**Issue by the-hotmann** [bingoohuang/go-utils#2]
I have the following and would like to decrypt the PBE, but in the readme there is no clear instruction on how to use this tool, it also does not let me import it in first place:

I have:
- pbe-encrypted-string
- pbe-password
- pbe-salt
- pbe-iteration-count

And would like to decrypt the encrypted string to plaintext.
But I already fail at importing this particular module:

```
go: finding module for package github.com/bingoohuang/gou
go_pbe_decrypt imports
        github.com/bingoohuang/gou: module github.com/bingoohuang/gou@latest found (v0.0.0-20210727012756-4873089fc9df), but does not contain package github.com/bingoohuang/gou
```

Could someone provide a good example on how to exactly use this module with some example code at [go.dev/play/](https://go.dev/play/)?

Thanks in advance!

**Comment by bingoohuang** [comment]
check the test file, pbewithmd5anddes_test.go

**Comment by MartinHotmann** [comment]
I have done this. But this does not answer the question on:

1. How to import the module
2. How to use it in go-code
3. if "plaintext" is the salt

It is very unclear on how to use this module in actual code.

**Comment by MartinHotmann** [comment]
I would like to decrypt a PBE which was encrypted through "PBEWITHSHA256AND256BITAES-BC" but I can't change the PBE Ciphers with this tool.
